<?php


namespace VlinkedUtils\Http;


use Throwable;

class HttpException extends \Exception
{
    public function __construct($message = "", $code = 0, Throwable $previous = null)
    {
        parent::__construct($message, $code, $previous);

    }

    public function __toString()
    {
        parent::__toString(); // TODO: Change the autogenerated stub
    }

    public function __wakeup()
    {
        parent::__wakeup(); // TODO: Change the autogenerated stub
    }

}